sudo: required
services:
  - docker

before_install:
  - docker build -t sudo: required
services:
  - docker

before_install:
  - docker build -t book-reservation -f ./Dockerfile ./

script:
  - docker run book-reservation npm test -- --coverage

after_success:
  - docker build -t book-reservation-server ./
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push book-reservation-server
