version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
    - mongo
    volumes:
      - /app/node_modules
      - ./:/usr/src/app
  mongo:
    image: mongo
    ports:
    - "27017:27017"