version: '2.4'
services:
  server:
    build: . 
    target: dev
    ports:
      - 5000:5000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment: 
      - NODE_ENV=development
  mongo:
    image: mongo
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1